# This file is used by Acquia Pipelines continuous integration. It builds
# Headless Lightning and runs its functional tests. Upon success, an artifact is
# deployed to the headlessnightly (f9b2254c-024f-4a28-bc14-fc1c06a495a6) sub on
# Acquia cloud.
version: 1.1.0
services:
  - mysql
  - php:
      version: 7.1

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/vendor/bin:$PATH"
            - composer validate --no-check-all --ansi
            - composer install
      - install:
          type: script
          script:
            - cd $SOURCE_DIR
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - lightning install 'mysql\://root:root@localhost/drupal' headless_lightning 'http://127.0.0.1:8080'
      - cleanup:
          type: script
          script:
            - cd $SOURCE_DIR
            # Setup settings file and codebase with minimum required for cloud.
            - lightning configure:cloud headlessnightly headless_lightning
