<?php

use Drupal\Core\Url;

/**
 * Implements hook_library_info_alter().
 */
function content_model_ui_library_info_alter(array &$libraries, $extension) {
  if ($extension == 'toolbar') {
    $path = drupal_get_path('module', 'content_model_ui');
    $url = Url::fromUri("internal:/$path/css/toolbar.css")->toString();

    $libraries['toolbar']['css']['theme'][$url] = [];
  }
}

/**
 * Implements template_preprocess_admin_block_content().
 */
function content_model_ui_preprocess_admin_block_content(array &$variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'admin.content_models') {
    // $variables['attributes']['class'][] = 'grid';
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function content_model_ui_menu_links_discovered_alter(array &$links) {
  $links['system.admin_structure']['enabled'] = FALSE;
}
