<?php

/**
 * Implements hook_help().
 */
function access_ui_help($route_name) {
  switch ($route_name) {
    case 'admin.access_control':
     return t('<p>Headless Lightning allows anonymous access to the API in the same way that Drupal allows anonymous access to content. Generally, published content is available while unpublished content is not. If your application needs more privileged access (for example, accessing unpublished or creating new content) you will need to authenticate. Authentication involves a client, which is associated with a role, and a user which is assigned the same role as the client. Once you have a client and user set up, you can authenticate like this:</p><pre><code>curl -X POST -d "grant_type=password&client_id=api_test{CLIENT_ID}&client_secret={SECRET}&username={USERNAME}&password={PASSWORD}" https://[YOURDOMAIN]/oauth/token</code></pre>');

    default:
      return NULL;
  }
}
